---
- name: Projet Load balancer
  hosts: all
  remote_user: vagrant
  become: true
  tasks:
  - name: Check connexion
    ping:
  #- name: Install Docker...
  #  shell: |
  #    curl -fsSL https://get.docker.com -o get-docker.sh
  #   sudo sh get-docker.sh
  - name: Get the git file from GitHub
    git: https://github.com/rtappa/repo_crash.git
      repo: 
      dest: /home/vagrant/projet/
  - name: run docker compose
    shell: 
      cmd: docker compose up --build -d --scale app=2
      chdir: projet
