---
- name: Projet Load balancer
  hosts: vpc-amel
  become: true
  tasks:
  - name: Check connexion
    ping:
  - name: Install Docker...
    shell: |
      curl -fsSL https://get.docker.com -o get-docker.sh
      sudo sh get-docker.sh
  - name: Get the git file from GitHub
    git:
      repo: https://github.com/AmelK17/test_crash_amel.git
      dest: /home/admin/projet/
  - name: run docker compose
    shell: 
      cmd: docker compose up --build -d --scale app=3
      chdir: projet
